### ISSUE TITLE
Can't install dash-extension

### ISSUE THREAD

**Issue by Saxamos** [emilhe/dash-extensions#346]
Hello,

While installing dash-extension, I have the following error:

```
Collecting jsbeautifier<2.0.0,>=1.14.3 (from dash-extensions==0.1.1)
  Using cached jsbeautifier-1.15.1.tar.gz (75 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-rg35dvoc/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-rg35dvoc/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-rg35dvoc/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-rg35dvoc/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 9, in <module>
      ModuleNotFoundError: No module named 'setuptools.command.test'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
I found this thread that seems related: https://stackoverflow.com/questions/78806100/no-module-named-setuptools-command-test

"It seems that their pip package is broken.
This is because setuptools.command.test was removed on 28 Jul 2024 (yesterday): https://setuptools.pypa.io/en/stable/history.html#v72-0-0"

**Comment by watson-sam** [comment]
This 100% should be fixed here so adding weight behind you issue, however to fix can find solutions here: https://github.com/pypa/setuptools/issues/4519

For poetry builds: 

Add to dockerfile:
```
ENV PIP_CONSTRAINT=constraints.txt
RUN pip install dash-extensions==WHATEVER
RUN poetry run pip install dash-extensions==WHATEVER
```

Having created and copied into dockerfile file called constraints.txt which contains: 
```
setuptools<72
```

**Comment by Saxamos** [comment]
Thank a lot!
